// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const REQUEST_TIMEOUT_MS = 12_000;

if (!SUPABASE_URL) {
  throw new Error("Missing VITE_SUPABASE_URL");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Missing VITE_SUPABASE_PUBLISHABLE_KEY");
}

function getProjectRef(url: string): string {
  try {
    return new URL(url).hostname.split(".")[0] ?? "unknown";
  } catch {
    return "invalid-url";
  }
}

const fetchWithTimeout: typeof fetch = async (input, init = {}) => {
  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => {
    controller.abort();
  }, REQUEST_TIMEOUT_MS);

  const externalSignal = init.signal;

  if (externalSignal) {
    if (externalSignal.aborted) {
      controller.abort();
    } else {
      externalSignal.addEventListener(
        "abort",
        () => {
          controller.abort();
        },
        { once: true },
      );
    }
  }

  try {
    return await fetch(input, {
      ...init,
      signal: controller.signal,
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new Error(
        `Supabase ne répond pas après ${Math.round(
          REQUEST_TIMEOUT_MS / 1000,
        )} secondes. Vérifie l'URL Supabase, la clé publishable, le réseau ou le déploiement Vercel.`,
      );
    }

    throw error;
  } finally {
    window.clearTimeout(timeoutId);
  }
};

export const supabaseRuntimeConfig = {
  url: SUPABASE_URL,
  projectRef: getProjectRef(SUPABASE_URL),
  keyPreview: `${SUPABASE_PUBLISHABLE_KEY.slice(0, 16)}…`,
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      fetch: fetchWithTimeout,
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
    },
  },
);
